// Code generated by qtc from "migration.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/migration.qtpl:1
package templates

//line templates/migration.qtpl:1
import "strings"

//line templates/migration.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/migration.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/migration.qtpl:2
func StreamGenMigration(qw422016 *qt422016.Writer, resourceName string) {
//line templates/migration.qtpl:3
	lcResourceName := strings.ToLower(resourceName)

//line templates/migration.qtpl:3
	qw422016.N().S(`
-- +goose Up
-- +goose StatementBegin
CREATE TABLE `)
//line templates/migration.qtpl:6
	qw422016.E().S(lcResourceName)
//line templates/migration.qtpl:6
	qw422016.N().S(`
(
    id         INT UNSIGNED NOT NULL AUTO_INCREMENT,
    created_at TIMESTAMP             DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    NOT NULL DEFAULT NOW() ON UPDATE NOW(),
    deleted_at TIMESTAMP    NULL,
    PRIMARY KEY (`)
//line templates/migration.qtpl:6
	qw422016.N().S("`")
//line templates/migration.qtpl:6
	qw422016.N().S(`id`)
//line templates/migration.qtpl:6
	qw422016.N().S("`")
//line templates/migration.qtpl:6
	qw422016.N().S(`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_general_ci;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS `)
//line templates/migration.qtpl:20
	qw422016.E().S(lcResourceName)
//line templates/migration.qtpl:20
	qw422016.N().S(`;
-- +goose StatementEnd
`)
//line templates/migration.qtpl:22
}

//line templates/migration.qtpl:22
func WriteGenMigration(qq422016 qtio422016.Writer, resourceName string) {
//line templates/migration.qtpl:22
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/migration.qtpl:22
	StreamGenMigration(qw422016, resourceName)
//line templates/migration.qtpl:22
	qt422016.ReleaseWriter(qw422016)
//line templates/migration.qtpl:22
}

//line templates/migration.qtpl:22
func GenMigration(resourceName string) string {
//line templates/migration.qtpl:22
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/migration.qtpl:22
	WriteGenMigration(qb422016, resourceName)
//line templates/migration.qtpl:22
	qs422016 := string(qb422016.B)
//line templates/migration.qtpl:22
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/migration.qtpl:22
	return qs422016
//line templates/migration.qtpl:22
}
