// Code generated by qtc from "resource.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/resource.qtpl:1
package templates

//line templates/resource.qtpl:1
import "strings"

//line templates/resource.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/resource.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/resource.qtpl:3
func StreamGenEntityErrors(qw422016 *qt422016.Writer) {
//line templates/resource.qtpl:3
	qw422016.N().S(`package entity

import "errors"

var ErrNotFound = errors.New("not found")
var ErrInvalidEntity = errors.New("invalid entity")
`)
//line templates/resource.qtpl:10
}

//line templates/resource.qtpl:10
func WriteGenEntityErrors(qq422016 qtio422016.Writer) {
//line templates/resource.qtpl:10
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/resource.qtpl:10
	StreamGenEntityErrors(qw422016)
//line templates/resource.qtpl:10
	qt422016.ReleaseWriter(qw422016)
//line templates/resource.qtpl:10
}

//line templates/resource.qtpl:10
func GenEntityErrors() string {
//line templates/resource.qtpl:10
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/resource.qtpl:10
	WriteGenEntityErrors(qb422016)
//line templates/resource.qtpl:10
	qs422016 := string(qb422016.B)
//line templates/resource.qtpl:10
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/resource.qtpl:10
	return qs422016
//line templates/resource.qtpl:10
}

//line templates/resource.qtpl:12
func StreamGenCustomEntity(qw422016 *qt422016.Writer, name string, fields []string) {
//line templates/resource.qtpl:13
	lcName := strings.ToLower(name)

//line templates/resource.qtpl:13
	qw422016.N().S(`
package entity

import (
	"time"
)

// `)
//line templates/resource.qtpl:20
	qw422016.E().S(name)
//line templates/resource.qtpl:20
	qw422016.N().S(` data
type `)
//line templates/resource.qtpl:21
	qw422016.E().S(name)
//line templates/resource.qtpl:21
	qw422016.N().S(` struct {
	ID        int
`)
//line templates/resource.qtpl:23
	for _, f := range fields {
//line templates/resource.qtpl:23
		qw422016.N().S(`

    `)
//line templates/resource.qtpl:25
	}
//line templates/resource.qtpl:25
	qw422016.N().S(`
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

// New`)
//line templates/resource.qtpl:31
	qw422016.E().S(name)
//line templates/resource.qtpl:31
	qw422016.N().S(` create a new `)
//line templates/resource.qtpl:31
	qw422016.E().S(lcName)
//line templates/resource.qtpl:31
	qw422016.N().S(`
func New`)
//line templates/resource.qtpl:32
	qw422016.E().S(name)
//line templates/resource.qtpl:32
	qw422016.N().S(`() (*`)
//line templates/resource.qtpl:32
	qw422016.E().S(name)
//line templates/resource.qtpl:32
	qw422016.N().S(`, error) {
	s := &`)
//line templates/resource.qtpl:33
	qw422016.E().S(name)
//line templates/resource.qtpl:33
	qw422016.N().S(`{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
	}

	if err := s.Validate(); err != nil {
		return nil, ErrInvalidEntity
	}
	return s, nil
}

func (s *`)
//line templates/resource.qtpl:44
	qw422016.E().S(name)
//line templates/resource.qtpl:44
	qw422016.N().S(`) Validate() error {
	return nil
}
`)
//line templates/resource.qtpl:47
}

//line templates/resource.qtpl:47
func WriteGenCustomEntity(qq422016 qtio422016.Writer, name string, fields []string) {
//line templates/resource.qtpl:47
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/resource.qtpl:47
	StreamGenCustomEntity(qw422016, name, fields)
//line templates/resource.qtpl:47
	qt422016.ReleaseWriter(qw422016)
//line templates/resource.qtpl:47
}

//line templates/resource.qtpl:47
func GenCustomEntity(name string, fields []string) string {
//line templates/resource.qtpl:47
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/resource.qtpl:47
	WriteGenCustomEntity(qb422016, name, fields)
//line templates/resource.qtpl:47
	qs422016 := string(qb422016.B)
//line templates/resource.qtpl:47
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/resource.qtpl:47
	return qs422016
//line templates/resource.qtpl:47
}

//line templates/resource.qtpl:49
func StreamGenTestCustomEntity(qw422016 *qt422016.Writer, projectName string, name string) {
//line templates/resource.qtpl:49
	qw422016.N().S(`package entity_test

import (
    "`)
//line templates/resource.qtpl:53
	qw422016.E().S(projectName)
//line templates/resource.qtpl:53
	qw422016.N().S(`/entity"
	"testing"

    "github.com/stretchr/testify/assert"
)

func TestNew`)
//line templates/resource.qtpl:59
	qw422016.E().S(name)
//line templates/resource.qtpl:59
	qw422016.N().S(`() (t *testing.T) {
	_, err := entity.New`)
//line templates/resource.qtpl:60
	qw422016.E().S(name)
//line templates/resource.qtpl:60
	qw422016.N().S(`()
	assert.Nil(t, err)
	return
}
`)
//line templates/resource.qtpl:64
}

//line templates/resource.qtpl:64
func WriteGenTestCustomEntity(qq422016 qtio422016.Writer, projectName string, name string) {
//line templates/resource.qtpl:64
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/resource.qtpl:64
	StreamGenTestCustomEntity(qw422016, projectName, name)
//line templates/resource.qtpl:64
	qt422016.ReleaseWriter(qw422016)
//line templates/resource.qtpl:64
}

//line templates/resource.qtpl:64
func GenTestCustomEntity(projectName string, name string) string {
//line templates/resource.qtpl:64
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/resource.qtpl:64
	WriteGenTestCustomEntity(qb422016, projectName, name)
//line templates/resource.qtpl:64
	qs422016 := string(qb422016.B)
//line templates/resource.qtpl:64
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/resource.qtpl:64
	return qs422016
//line templates/resource.qtpl:64
}

//line templates/resource.qtpl:66
func StreamGenEntityUsecaseInterface(qw422016 *qt422016.Writer, projectName string, name string) {
//line templates/resource.qtpl:68
	lcName := strings.ToLower(name)

//line templates/resource.qtpl:69
	qw422016.N().S(`
package `)
//line templates/resource.qtpl:70
	qw422016.E().S(lcName)
//line templates/resource.qtpl:70
	qw422016.N().S(`

import (
	"context"
	"`)
//line templates/resource.qtpl:74
	qw422016.E().S(projectName)
//line templates/resource.qtpl:74
	qw422016.N().S(`/entity"
)

type Reader interface {
	Get(ctx context.Context, id entity.ID) (*entity.`)
//line templates/resource.qtpl:78
	qw422016.E().S(name)
//line templates/resource.qtpl:78
	qw422016.N().S(`, error)
	List(ctx context.Context) ([]*entity.`)
//line templates/resource.qtpl:79
	qw422016.E().S(name)
//line templates/resource.qtpl:79
	qw422016.N().S(`, error)
}

type Writer interface {
	Create(ctx context.Context, e *entity.`)
//line templates/resource.qtpl:83
	qw422016.E().S(name)
//line templates/resource.qtpl:83
	qw422016.N().S(`) (entity.ID, error)
	Update(ctx context.Context, e *entity.`)
//line templates/resource.qtpl:84
	qw422016.E().S(name)
//line templates/resource.qtpl:84
	qw422016.N().S(`) error
	Delete(ctx context.Context, id entity.ID) error
}

type Repository interface {
	Reader
	Writer
}

type UseCase interface {
	Create`)
//line templates/resource.qtpl:94
	qw422016.E().S(name)
//line templates/resource.qtpl:94
	qw422016.N().S(`(ctx context.Context) (entity.ID, error)
	Get`)
//line templates/resource.qtpl:95
	qw422016.E().S(name)
//line templates/resource.qtpl:95
	qw422016.N().S(`(ctx context.Context, id entity.ID) (*entity.`)
//line templates/resource.qtpl:95
	qw422016.E().S(name)
//line templates/resource.qtpl:95
	qw422016.N().S(`, error)
	List`)
//line templates/resource.qtpl:96
	qw422016.E().S(name)
//line templates/resource.qtpl:96
	qw422016.N().S(`s(ctx context.Context) ([]*entity.`)
//line templates/resource.qtpl:96
	qw422016.E().S(name)
//line templates/resource.qtpl:96
	qw422016.N().S(`, error)
	Update`)
//line templates/resource.qtpl:97
	qw422016.E().S(name)
//line templates/resource.qtpl:97
	qw422016.N().S(`(ctx context.Context, e *entity.`)
//line templates/resource.qtpl:97
	qw422016.E().S(name)
//line templates/resource.qtpl:97
	qw422016.N().S(`) error
}
`)
//line templates/resource.qtpl:99
}

//line templates/resource.qtpl:99
func WriteGenEntityUsecaseInterface(qq422016 qtio422016.Writer, projectName string, name string) {
//line templates/resource.qtpl:99
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/resource.qtpl:99
	StreamGenEntityUsecaseInterface(qw422016, projectName, name)
//line templates/resource.qtpl:99
	qt422016.ReleaseWriter(qw422016)
//line templates/resource.qtpl:99
}

//line templates/resource.qtpl:99
func GenEntityUsecaseInterface(projectName string, name string) string {
//line templates/resource.qtpl:99
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/resource.qtpl:99
	WriteGenEntityUsecaseInterface(qb422016, projectName, name)
//line templates/resource.qtpl:99
	qs422016 := string(qb422016.B)
//line templates/resource.qtpl:99
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/resource.qtpl:99
	return qs422016
//line templates/resource.qtpl:99
}

//line templates/resource.qtpl:101
func StreamGenEntityUsecaseService(qw422016 *qt422016.Writer, projectName string, name string) {
//line templates/resource.qtpl:102
	lcName := strings.ToLower(name)

//line templates/resource.qtpl:102
	qw422016.N().S(`
package `)
//line templates/resource.qtpl:103
	qw422016.E().S(lcName)
//line templates/resource.qtpl:103
	qw422016.N().S(`

import (
	"context"
	"`)
//line templates/resource.qtpl:107
	qw422016.E().S(projectName)
//line templates/resource.qtpl:107
	qw422016.N().S(`/entity"
	"time"
)

type Service struct {
	repo Repository
}

// New`)
//line templates/resource.qtpl:115
	qw422016.E().S(name)
//line templates/resource.qtpl:115
	qw422016.N().S(` create a new `)
//line templates/resource.qtpl:115
	qw422016.E().S(lcName)
//line templates/resource.qtpl:115
	qw422016.N().S(`
func New`)
//line templates/resource.qtpl:116
	qw422016.E().S(name)
//line templates/resource.qtpl:116
	qw422016.N().S(`(r Repository) *`)
//line templates/resource.qtpl:116
	qw422016.E().S(name)
//line templates/resource.qtpl:116
	qw422016.N().S(` {
	return &`)
//line templates/resource.qtpl:117
	qw422016.E().S(name)
//line templates/resource.qtpl:117
	qw422016.N().S(`{
		repo: r,
	}
}

// Create`)
//line templates/resource.qtpl:122
	qw422016.E().S(name)
//line templates/resource.qtpl:122
	qw422016.N().S(` create a `)
//line templates/resource.qtpl:122
	qw422016.E().S(lcName)
//line templates/resource.qtpl:122
	qw422016.N().S(`
func (s *Service) Create`)
//line templates/resource.qtpl:123
	qw422016.E().S(name)
//line templates/resource.qtpl:123
	qw422016.N().S(`(ctx context.Context) (entity.ID, error) {
	sub, err := entity.New`)
//line templates/resource.qtpl:124
	qw422016.E().S(name)
//line templates/resource.qtpl:124
	qw422016.N().S(`()
	if err != nil {
		return sub.ID, err
	}
	return s.repo.Create(ctx, sub)
}

// Get`)
//line templates/resource.qtpl:131
	qw422016.E().S(name)
//line templates/resource.qtpl:131
	qw422016.N().S(` get a `)
//line templates/resource.qtpl:131
	qw422016.E().S(lcName)
//line templates/resource.qtpl:131
	qw422016.N().S(`
func (s *Service) Get`)
//line templates/resource.qtpl:132
	qw422016.E().S(name)
//line templates/resource.qtpl:132
	qw422016.N().S(`(ctx context.Context, id entity.ID) (*entity.`)
//line templates/resource.qtpl:132
	qw422016.E().S(name)
//line templates/resource.qtpl:132
	qw422016.N().S(`, error) {
	sub, err := s.repo.Get(ctx, id)
	if sub == nil {
		return nil, entity.ErrNotFound
	}
	if err != nil {
		return nil, err
	}
	return sub, nil
}

// List`)
//line templates/resource.qtpl:143
	qw422016.E().S(name)
//line templates/resource.qtpl:143
	qw422016.N().S(`s list `)
//line templates/resource.qtpl:143
	qw422016.E().S(lcName)
//line templates/resource.qtpl:143
	qw422016.N().S(`s
func (s *Service) List`)
//line templates/resource.qtpl:144
	qw422016.E().S(name)
//line templates/resource.qtpl:144
	qw422016.N().S(`s(ctx context.Context) ([]*entity.`)
//line templates/resource.qtpl:144
	qw422016.E().S(name)
//line templates/resource.qtpl:144
	qw422016.N().S(`, error) {
	subs, err := s.repo.List(ctx)
	if err != nil {
		return nil, err
	}
	return subs, nil
}

// Update`)
//line templates/resource.qtpl:152
	qw422016.E().S(name)
//line templates/resource.qtpl:152
	qw422016.N().S(` update a `)
//line templates/resource.qtpl:152
	qw422016.E().S(lcName)
//line templates/resource.qtpl:152
	qw422016.N().S(`
func (s *Service) UpdateSubject(ctx context.Context, e *entity.`)
//line templates/resource.qtpl:153
	qw422016.E().S(name)
//line templates/resource.qtpl:153
	qw422016.N().S(`) error {
	if err := e.Validate(); err != nil {
		return err
	}
	e.UpdatedAt = time.Now()
	return s.repo.Update(ctx, e)
}

`)
//line templates/resource.qtpl:161
}

//line templates/resource.qtpl:161
func WriteGenEntityUsecaseService(qq422016 qtio422016.Writer, projectName string, name string) {
//line templates/resource.qtpl:161
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/resource.qtpl:161
	StreamGenEntityUsecaseService(qw422016, projectName, name)
//line templates/resource.qtpl:161
	qt422016.ReleaseWriter(qw422016)
//line templates/resource.qtpl:161
}

//line templates/resource.qtpl:161
func GenEntityUsecaseService(projectName string, name string) string {
//line templates/resource.qtpl:161
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/resource.qtpl:161
	WriteGenEntityUsecaseService(qb422016, projectName, name)
//line templates/resource.qtpl:161
	qs422016 := string(qb422016.B)
//line templates/resource.qtpl:161
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/resource.qtpl:161
	return qs422016
//line templates/resource.qtpl:161
}

//line templates/resource.qtpl:163
func StreamGenEntityRepository(qw422016 *qt422016.Writer, projectName string, name string) {
//line templates/resource.qtpl:163
	qw422016.N().S(`package repository
`)
//line templates/resource.qtpl:165
	lcName := strings.ToLower(name)

//line templates/resource.qtpl:165
	qw422016.N().S(`

import (
	"context"
	"fmt"
	sq "github.com/Masterminds/squirrel"
	"github.com/jmoiron/sqlx"
	"`)
//line templates/resource.qtpl:172
	qw422016.E().S(projectName)
//line templates/resource.qtpl:172
	qw422016.N().S(`/entity"
	"time"
)

type `)
//line templates/resource.qtpl:176
	qw422016.E().S(name)
//line templates/resource.qtpl:176
	qw422016.N().S(`Repo struct {
	db *sqlx.DB
}

// New`)
//line templates/resource.qtpl:180
	qw422016.E().S(name)
//line templates/resource.qtpl:180
	qw422016.N().S(`Repo create a new repository
func New`)
//line templates/resource.qtpl:181
	qw422016.E().S(name)
//line templates/resource.qtpl:181
	qw422016.N().S(`Repo(db *sqlx.DB) *`)
//line templates/resource.qtpl:181
	qw422016.E().S(name)
//line templates/resource.qtpl:181
	qw422016.N().S(`Repo {
	return &`)
//line templates/resource.qtpl:182
	qw422016.E().S(name)
//line templates/resource.qtpl:182
	qw422016.N().S(`Repo{
		db: db,
	}
}

// Create a `)
//line templates/resource.qtpl:187
	qw422016.E().S(lcName)
//line templates/resource.qtpl:187
	qw422016.N().S(`
func (r *`)
//line templates/resource.qtpl:188
	qw422016.E().S(name)
//line templates/resource.qtpl:188
	qw422016.N().S(`Repo) Create(ctx context.Context, e *entity.`)
//line templates/resource.qtpl:188
	qw422016.E().S(name)
//line templates/resource.qtpl:188
	qw422016.N().S(`) (entity.ID, error) {
	err := sq.
		Insert("`)
//line templates/resource.qtpl:190
	qw422016.E().S(lcName)
//line templates/resource.qtpl:190
	qw422016.N().S(`").
		// Columns("id", "title", "description").
		// Values(e.ID, e.Title, e.Description).
		// Suffix("RETURNING \"id\""). // postgres only
		RunWith(r.db).
		ScanContext(ctx, &e)

	if err != nil {
		return e.ID, err
	}

	return e.ID, nil
}

// Get a `)
//line templates/resource.qtpl:204
	qw422016.E().S(lcName)
//line templates/resource.qtpl:204
	qw422016.N().S(`
func (r *`)
//line templates/resource.qtpl:205
	qw422016.E().S(name)
//line templates/resource.qtpl:205
	qw422016.N().S(`Repo) Get(ctx context.Context, id entity.ID) (*entity.`)
//line templates/resource.qtpl:205
	qw422016.E().S(name)
//line templates/resource.qtpl:205
	qw422016.N().S(`, error) {
	var `)
//line templates/resource.qtpl:206
	qw422016.E().S(lcName)
//line templates/resource.qtpl:206
	qw422016.N().S(` entity.`)
//line templates/resource.qtpl:206
	qw422016.E().S(name)
//line templates/resource.qtpl:206
	qw422016.N().S(`
	err := sq.
		Select("title", "description", "created_at", "updated_at").
		From("`)
//line templates/resource.qtpl:209
	qw422016.E().S(lcName)
//line templates/resource.qtpl:209
	qw422016.N().S(`").
		Where(sq.Eq{"id": id}).
		Where(sq.Eq{"deleted_at": nil}).
		Limit(1).
		ScanContext(ctx, &`)
//line templates/resource.qtpl:213
	qw422016.E().S(lcName)
//line templates/resource.qtpl:213
	qw422016.N().S(`)
	if err != nil {
		return nil, err
	}
	return &`)
//line templates/resource.qtpl:217
	qw422016.E().S(lcName)
//line templates/resource.qtpl:217
	qw422016.N().S(`, err
}

// Update a `)
//line templates/resource.qtpl:220
	qw422016.E().S(lcName)
//line templates/resource.qtpl:220
	qw422016.N().S(`
func (r *`)
//line templates/resource.qtpl:221
	qw422016.E().S(name)
//line templates/resource.qtpl:221
	qw422016.N().S(`Repo) Update(ctx context.Context, e *entity.`)
//line templates/resource.qtpl:221
	qw422016.E().S(name)
//line templates/resource.qtpl:221
	qw422016.N().S(`) error {
	e.UpdatedAt = time.Now()
	_, err := sq.
		Update("`)
//line templates/resource.qtpl:224
	qw422016.E().S(lcName)
//line templates/resource.qtpl:224
	qw422016.N().S(`").
		Set("title", e.Title).
		Set("description", e.Description).
		Set("updated_at", e.UpdatedAt).
		Where(sq.Eq{"id": e.ID}).ExecContext(ctx)
	if err != nil {
		return err
	}
	return nil
}

// List `)
//line templates/resource.qtpl:235
	qw422016.E().S(lcName)
//line templates/resource.qtpl:235
	qw422016.N().S(`s
func (r *`)
//line templates/resource.qtpl:236
	qw422016.E().S(name)
//line templates/resource.qtpl:236
	qw422016.N().S(`Repo) List(ctx context.Context) ([]*entity.`)
//line templates/resource.qtpl:236
	qw422016.E().S(name)
//line templates/resource.qtpl:236
	qw422016.N().S(`, error) {
	tx, _ := r.db.Begin()

	var `)
//line templates/resource.qtpl:239
	qw422016.E().S(lcName)
//line templates/resource.qtpl:239
	qw422016.N().S(`s []*entity.`)
//line templates/resource.qtpl:239
	qw422016.E().S(name)
//line templates/resource.qtpl:239
	qw422016.N().S(`
	sql, _, err := sq.
		Select("id", "title", "description", "created_at", "updated_at").
		From("`)
//line templates/resource.qtpl:242
	qw422016.E().S(lcName)
//line templates/resource.qtpl:242
	qw422016.N().S(`").
		Limit(30). // TODO needs to come from pagination
		ToSql()
	if err != nil {
		return nil, err
	}

	rows, err := tx.QueryContext(ctx, sql)
	if err != nil {
		return nil, err
	}

	for rows.Next() {
		var `)
//line templates/resource.qtpl:255
	qw422016.E().S(lcName)
//line templates/resource.qtpl:255
	qw422016.N().S(` entity.`)
//line templates/resource.qtpl:255
	qw422016.E().S(name)
//line templates/resource.qtpl:255
	qw422016.N().S(`
		_ = rows.Scan(
			&`)
//line templates/resource.qtpl:257
	qw422016.E().S(lcName)
//line templates/resource.qtpl:257
	qw422016.N().S(`.ID,
			&`)
//line templates/resource.qtpl:258
	qw422016.E().S(lcName)
//line templates/resource.qtpl:258
	qw422016.N().S(`.Title,
			&`)
//line templates/resource.qtpl:259
	qw422016.E().S(lcName)
//line templates/resource.qtpl:259
	qw422016.N().S(`.Description,
			&`)
//line templates/resource.qtpl:260
	qw422016.E().S(lcName)
//line templates/resource.qtpl:260
	qw422016.N().S(`.CreatedAt,
			&`)
//line templates/resource.qtpl:261
	qw422016.E().S(lcName)
//line templates/resource.qtpl:261
	qw422016.N().S(`.UpdatedAt,
		)
		`)
//line templates/resource.qtpl:263
	qw422016.E().S(lcName)
//line templates/resource.qtpl:263
	qw422016.N().S(`s = append(`)
//line templates/resource.qtpl:263
	qw422016.E().S(lcName)
//line templates/resource.qtpl:263
	qw422016.N().S(`s, &`)
//line templates/resource.qtpl:263
	qw422016.E().S(lcName)
//line templates/resource.qtpl:263
	qw422016.N().S(`)
	}
	return `)
//line templates/resource.qtpl:265
	qw422016.E().S(lcName)
//line templates/resource.qtpl:265
	qw422016.N().S(`s, nil
}

// Delete `)
//line templates/resource.qtpl:268
	qw422016.E().S(lcName)
//line templates/resource.qtpl:268
	qw422016.N().S(`s
func (r *`)
//line templates/resource.qtpl:269
	qw422016.E().S(name)
//line templates/resource.qtpl:269
	qw422016.N().S(`Repo) Delete(ctx context.Context, id entity.ID) error {
	_, err := sq.
		Delete("`)
//line templates/resource.qtpl:271
	qw422016.E().S(lcName)
//line templates/resource.qtpl:271
	qw422016.N().S(`").
		Where(sq.Eq{"id": id}).
		Limit(1).
		ExecContext(ctx)
	if err != nil {
		return err
	}
	return nil
}
`)
//line templates/resource.qtpl:280
}

//line templates/resource.qtpl:280
func WriteGenEntityRepository(qq422016 qtio422016.Writer, projectName string, name string) {
//line templates/resource.qtpl:280
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/resource.qtpl:280
	StreamGenEntityRepository(qw422016, projectName, name)
//line templates/resource.qtpl:280
	qt422016.ReleaseWriter(qw422016)
//line templates/resource.qtpl:280
}

//line templates/resource.qtpl:280
func GenEntityRepository(projectName string, name string) string {
//line templates/resource.qtpl:280
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/resource.qtpl:280
	WriteGenEntityRepository(qb422016, projectName, name)
//line templates/resource.qtpl:280
	qs422016 := string(qb422016.B)
//line templates/resource.qtpl:280
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/resource.qtpl:280
	return qs422016
//line templates/resource.qtpl:280
}

//line templates/resource.qtpl:282
func StreamGenResourceHandler(qw422016 *qt422016.Writer, moduleName, resourceName string) {
//line templates/resource.qtpl:282
	qw422016.N().S(`package handler
`)
//line templates/resource.qtpl:284
	lcResourceName := strings.ToLower(resourceName)

//line templates/resource.qtpl:284
	qw422016.N().S(`
import (
	"github.com/go-playground/validator/v10"
	"github.com/gofiber/fiber/v2"
	"`)
//line templates/resource.qtpl:288
	qw422016.E().S(moduleName)
//line templates/resource.qtpl:288
	qw422016.N().S(`/api/presenter"
	"`)
//line templates/resource.qtpl:289
	qw422016.E().S(moduleName)
//line templates/resource.qtpl:289
	qw422016.N().S(`/entity"
	"`)
//line templates/resource.qtpl:290
	qw422016.E().S(moduleName)
//line templates/resource.qtpl:290
	qw422016.N().S(`/usecase/`)
//line templates/resource.qtpl:290
	qw422016.E().S(lcResourceName)
//line templates/resource.qtpl:290
	qw422016.N().S(`"
)

func New`)
//line templates/resource.qtpl:293
	qw422016.E().S(resourceName)
//line templates/resource.qtpl:293
	qw422016.N().S(`Handlers(r fiber.Router, service `)
//line templates/resource.qtpl:293
	qw422016.E().S(lcResourceName)
//line templates/resource.qtpl:293
	qw422016.N().S(`.UseCase, v *validator.Validate) {
	r.Get("", list`)
//line templates/resource.qtpl:294
	qw422016.E().S(resourceName)
//line templates/resource.qtpl:294
	qw422016.N().S(`s(service))
	r.Post("", create`)
//line templates/resource.qtpl:295
	qw422016.E().S(resourceName)
//line templates/resource.qtpl:295
	qw422016.N().S(`(service, v))
}

func list`)
//line templates/resource.qtpl:298
	qw422016.E().S(resourceName)
//line templates/resource.qtpl:298
	qw422016.N().S(`s(service `)
//line templates/resource.qtpl:298
	qw422016.E().S(lcResourceName)
//line templates/resource.qtpl:298
	qw422016.N().S(`.UseCase) fiber.Handler {
	return func(ctx *fiber.Ctx) error {
		var data []*entity.`)
//line templates/resource.qtpl:300
	qw422016.E().S(resourceName)
//line templates/resource.qtpl:300
	qw422016.N().S(`

		data, err := service.List`)
//line templates/resource.qtpl:302
	qw422016.E().S(resourceName)
//line templates/resource.qtpl:302
	qw422016.N().S(`s(ctx.Context())
		if err != nil {
			return ctx.Status(fiber.StatusInternalServerError).JSON(err)
		}

		var toJ []*presenter.`)
//line templates/resource.qtpl:307
	qw422016.E().S(resourceName)
//line templates/resource.qtpl:307
	qw422016.N().S(`
		for _, d := range data {
			toJ = append(toJ, &presenter.`)
//line templates/resource.qtpl:309
	qw422016.E().S(resourceName)
//line templates/resource.qtpl:309
	qw422016.N().S(`{
				ID:          d.ID,
				CreatedAt:   d.CreatedAt,
				UpdatedAt:   d.UpdatedAt,
			})
		}

		return ctx.Status(fiber.StatusOK).JSON(toJ)
	}
}

func create`)
//line templates/resource.qtpl:320
	qw422016.E().S(resourceName)
//line templates/resource.qtpl:320
	qw422016.N().S(`(service `)
//line templates/resource.qtpl:320
	qw422016.E().S(lcResourceName)
//line templates/resource.qtpl:320
	qw422016.N().S(`.UseCase, v *validator.Validate) fiber.Handler {
	return func(ctx *fiber.Ctx) error {
		var body struct {
			Title       string `)
//line templates/resource.qtpl:320
	qw422016.N().S("`")
//line templates/resource.qtpl:320
	qw422016.N().S(`json:"title" validate:"required"`)
//line templates/resource.qtpl:320
	qw422016.N().S("`")
//line templates/resource.qtpl:320
	qw422016.N().S(`
			Description string `)
//line templates/resource.qtpl:320
	qw422016.N().S("`")
//line templates/resource.qtpl:320
	qw422016.N().S(`json:"description" validate:"required"`)
//line templates/resource.qtpl:320
	qw422016.N().S("`")
//line templates/resource.qtpl:320
	qw422016.N().S(`
		}

		if err := ctx.BodyParser(&body); err != nil {
			return ctx.
				Status(fiber.StatusInternalServerError).
				JSON("Error adding `)
//line templates/resource.qtpl:330
	qw422016.E().S(lcResourceName)
//line templates/resource.qtpl:330
	qw422016.N().S(`")
		}

		if err := v.StructCtx(ctx.Context(), &body); err != nil {
			return ctx.Status(fiber.StatusBadRequest).JSON(err)
		}

		id, err := service.Create`)
//line templates/resource.qtpl:337
	qw422016.E().S(resourceName)
//line templates/resource.qtpl:337
	qw422016.N().S(`(ctx.Context())
		if err != nil {
			return ctx.
				Status(fiber.StatusInternalServerError).
				JSON("Error adding `)
//line templates/resource.qtpl:341
	qw422016.E().S(lcResourceName)
//line templates/resource.qtpl:341
	qw422016.N().S(`")
		}

		item, err := service.Get`)
//line templates/resource.qtpl:344
	qw422016.E().S(resourceName)
//line templates/resource.qtpl:344
	qw422016.N().S(`(ctx.Context(), id)
		if err != nil {
			return ctx.Status(fiber.StatusInternalServerError).JSON("Error adding `)
//line templates/resource.qtpl:346
	qw422016.E().S(lcResourceName)
//line templates/resource.qtpl:346
	qw422016.N().S(`")
		}

		toJ := &presenter.`)
//line templates/resource.qtpl:349
	qw422016.E().S(resourceName)
//line templates/resource.qtpl:349
	qw422016.N().S(`{
			ID:          item.ID,
			CreatedAt:   item.CreatedAt,
			UpdatedAt:   item.UpdatedAt,
		}
		return ctx.Status(fiber.StatusCreated).JSON(toJ)
	}
}
`)
//line templates/resource.qtpl:357
}

//line templates/resource.qtpl:357
func WriteGenResourceHandler(qq422016 qtio422016.Writer, moduleName, resourceName string) {
//line templates/resource.qtpl:357
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/resource.qtpl:357
	StreamGenResourceHandler(qw422016, moduleName, resourceName)
//line templates/resource.qtpl:357
	qt422016.ReleaseWriter(qw422016)
//line templates/resource.qtpl:357
}

//line templates/resource.qtpl:357
func GenResourceHandler(moduleName, resourceName string) string {
//line templates/resource.qtpl:357
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/resource.qtpl:357
	WriteGenResourceHandler(qb422016, moduleName, resourceName)
//line templates/resource.qtpl:357
	qs422016 := string(qb422016.B)
//line templates/resource.qtpl:357
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/resource.qtpl:357
	return qs422016
//line templates/resource.qtpl:357
}

//line templates/resource.qtpl:359
func StreamGenResourcePresenter(qw422016 *qt422016.Writer, moduleName, resourceName string) {
//line templates/resource.qtpl:359
	qw422016.N().S(`package presenter

import (
	"`)
//line templates/resource.qtpl:363
	qw422016.E().S(moduleName)
//line templates/resource.qtpl:363
	qw422016.N().S(`/entity"
	"time"
)

type `)
//line templates/resource.qtpl:367
	qw422016.E().S(resourceName)
//line templates/resource.qtpl:367
	qw422016.N().S(` struct {
	ID          entity.ID `)
//line templates/resource.qtpl:367
	qw422016.N().S("`")
//line templates/resource.qtpl:367
	qw422016.N().S(`json:"id"`)
//line templates/resource.qtpl:367
	qw422016.N().S("`")
//line templates/resource.qtpl:367
	qw422016.N().S(`
	CreatedAt   time.Time `)
//line templates/resource.qtpl:367
	qw422016.N().S("`")
//line templates/resource.qtpl:367
	qw422016.N().S(`json:"createdAt"`)
//line templates/resource.qtpl:367
	qw422016.N().S("`")
//line templates/resource.qtpl:367
	qw422016.N().S(`
	UpdatedAt   time.Time `)
//line templates/resource.qtpl:367
	qw422016.N().S("`")
//line templates/resource.qtpl:367
	qw422016.N().S(`json:"updatedAt"`)
//line templates/resource.qtpl:367
	qw422016.N().S("`")
//line templates/resource.qtpl:367
	qw422016.N().S(`
}
`)
//line templates/resource.qtpl:372
}

//line templates/resource.qtpl:372
func WriteGenResourcePresenter(qq422016 qtio422016.Writer, moduleName, resourceName string) {
//line templates/resource.qtpl:372
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/resource.qtpl:372
	StreamGenResourcePresenter(qw422016, moduleName, resourceName)
//line templates/resource.qtpl:372
	qt422016.ReleaseWriter(qw422016)
//line templates/resource.qtpl:372
}

//line templates/resource.qtpl:372
func GenResourcePresenter(moduleName, resourceName string) string {
//line templates/resource.qtpl:372
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/resource.qtpl:372
	WriteGenResourcePresenter(qb422016, moduleName, resourceName)
//line templates/resource.qtpl:372
	qs422016 := string(qb422016.B)
//line templates/resource.qtpl:372
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/resource.qtpl:372
	return qs422016
//line templates/resource.qtpl:372
}
